### ISSUE TITLE
RF_MSE worst score says 0.3 but experiments show it is 0.1

### ISSUE THREAD

**Issue by KristianKalinak** [dynverse/dyneval#58]
Hello,

I have been using your dyneval package and as part of my project I compare models to one another, and even in completely disjoint predicted trajectories, the score output from rf_mse peaked around 0.1, never receiving a score higher than that.

In your documentation for metrics, you list the perfect score for rf_mse to be 0 (which works) but the worst score is supposedly 0.3.
I decided to use the rf_nmse function (normalized to range [1,0]) and when ran on the same two disjoint trajectories rf_mse return 0.0989 and rf_nmse around 0, indicating that 0.1 is indeed the worst score (rf_mse score of 0 resulted in rf_nmse of 1 so that works correctly).

Am I doing something wrong is it there simply a mistake in the documentation?

**Comment by zouter** [comment]
Hi @Narrik 

The rf_mse score has no upper bound, so this 0.3 is some random value that we chose that was typically the limit on our datasets. So you're doing nothing wrong! It might be that in your case, something around 0.1 is the most extreme value, and that everything below that is better.

If you want to find this "upper bound" automatically, you might want to use the rf_mse score after you randomly shuffled the cells. This will give you a rough estimate, although in some very bad cases the rf_mse might still be a bit higher.

(The reason we still added a maximum value here is because we use this value in some of our plots as the axes limits).
